apiVersion: v1
kind: ConfigMap
metadata:
  name: config-v
  namespace: test-space
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8080;
        location / {
          return 200 'Hello from custom NGINX config\n';
        }
      }
    }
