apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrole-binding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: test-sa
    namespace: dev-space
roleRef:
  kind: ClusterRole
  name: cluster-role
  apiGroup: rbac.authorization.k8s.io
