apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods", "deployemnts", "statefulsets"]
  verbs: ["list", "get", "watch"]


