apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-test
  namespace: dev-space
subjects:
- kind: ServiceAccount
  name: test-sa
  namespace: dev-space
roleRef:
  kind: Role
  name: role-test
  apiGroup: rbac.authorization.k8s.io
