apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-test
  namespace: dev-space
  labels:
    pod: mypod
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: mypod
  serviceName: svc-test
  template:
    metadata:
      labels:
        pod: mypod
    spec:
      serviceAccountName: test-sa
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: volume
              mountPath: /data/state
      volumes:
      - name: volume
        hostPath:
          path: /data/state
          type: DirectoryOrCreate

