apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa_initial
  namespace: devops-space
  labels:
    pod: mypod
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vpa-deploy
  updatePolicy:
    updateMode: "initial"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources: ["cpu", "memory"]
      minAllowed:
        cpu: "100m"
        memory: "128Mi"
      maxAllowed:
        cpu: "500m"
        memory: "500Mi"
