apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-pod
  namespace: dev-space
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
  nodeSelector:
    type: docker-desktop
