FROM python:3.12-alpine

WORKDIR /app

EXPOSE 8000

RUN apk add --no-cache wget

CMD ["python3", "-m", "http.server"]

HEALTHCHECK --interval=5s --start-period=5s --timeout=3s --retries=3 \
          CMD wget --spider -q http://localhost:8000 || exit 1
