apiVersion: v1
kind: Namespace
metadata:
  name: dev-space

---

apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: dev-space
  labels:
    myapp: app
spec:
  containers:
    - name: nginx
      image: nginx
