apiVersion: v1
kind: Pod
metadata:
  name: secret-test
  namespace: test-space
  labels:
    pod: mypod
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "echo this the password $password && sleep 40"]
      env:
        - name: password
          valueFrom:
            secretKeyRef:
              name: secret-test
              key: password
