apiVersion: v1
kind: Service
metadata:
  namespace: dev-space
  labels:
    myservice: service
  name: cluster-service
spec:
  type: ClusterIP
  selector:
    myapp: app
  ports:
    - name: service
      port: 3000
      targetPort: 80
