apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-deploy
  namespace: practice-space
  labels:
    pod: mypod
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: mypod
  template:
    metadata:
      labels:
        pod: mypod
    spec:
      containers:
        - name: apache2
          image: httpd
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: hostpath
              mountPath: /data
      volumes:
        - name: hostpath
          hostPath:
            path: /pod/hostpath
            type: DirectoryOrCreate
