apiVersion: v1
kind: Namespace
metadata:
  name: practice-space
---

apiVersion: v1
kind: Pod
metadata:
  name: health-pod
  namespace: practice-space
  labels:
    pod: mypod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 20
        timeoutSeconds: 10
        periodSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 20
        timeoutSeconds: 10
        periodSeconds: 5
        failureThreshold: 3
