apiVersion: v1
kind: Pod
metadata:
  name: pod-pv-pvc
  namespace: practice-space
  labels:
    pod: mypod
spec:
  containers:
    - name: test
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pv-pvc
          mountPath: /pv/data
  volumes:
    - name: pv-pvc
      persistentVolumeClaim:
        claimName: pvc

