apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: practice-space
  labels:
    pod: mypod
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath-pv
  hostPath:
    path: /pvc/data

