apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: practice-space
  labels:
    pod: mypod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: hostpath-pv
